language: python
python:
 - "3.6"
addons:
  apt:
    packages:
      - openjdk-8-jre
branches:
  only:
    - master
install:
  - pip install 'html5validator ~= 0.3.1'
script:
  - html5validator --show-warnings --match index.html --root .
  - gpg --recv-keys A3E0EF6CECB33C342AA6EC7C5508153A6E7FC5FB
  - gpg --verify index.html.asc index.html
